# Generated by Django 5.0.1 on 2024-02-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffers',
            name='Province',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
