# Generated by Django 5.0.1 on 2024-02-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_joboffers_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffers',
            name='Average_Earnings',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='joboffers',
            name='LocationLatitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='joboffers',
            name='LocationLongitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='joboffers',
            name='Max_Earnings',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='joboffers',
            name='Min_Earnings',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True),
        ),
    ]
