# Generated by Django 5.0.1 on 2024-02-29 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_joboffers_average_earnings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joboffers',
            old_name='LocationLatitude',
            new_name='Location_Latitude',
        ),
        migrations.RenameField(
            model_name='joboffers',
            old_name='LocationLongitude',
            new_name='Location_Longitude',
        ),
    ]
