# Generated by Django 5.0.1 on 2024-03-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_locationlatitude_joboffers_location_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffers',
            name='Earnings_Range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='joboffers',
            name='Earnings_Type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
