manual_provinces = {
    "Katowice": "województwo śląskie",
    "Bielsko-Biała": "województwo śląskie",
    "Goczałkowice-Zdrój": "województwo śląskie",
    "Tychy": "województwo śląskie",
    "Gliwice": "województwo śląskie",
    "Żywiec": "województwo śląskie",
    "Mikołów": "województwo śląskie",
    "Pszczyna": "województwo śląskie",
    "Częstochowa": "województwo śląskie",
    "Chorzów": "województwo śląskie",
    "Jaworzno": "województwo śląskie",
    "Milówka": "województwo śląskie",
    "Bytom": "województwo śląskie",
    "Myszków": "województwo śląskie",
    "Rajcza": "województwo śląskie",
    "Miasteczko Śląskie": "województwo śląskie",
    "Sosnowiec": "województwo śląskie",
    "Siemianowice Śląskie": "województwo śląskie",
    "Ruda Śląska": "województwo śląskie",
    "Tarnowskie Góry": "województwo śląskie",
    "Czeladź": "województwo śląskie",
    "Mysłowice": "województwo śląskie",
    "Czerwionka-Leszczyny": "województwo śląskie",
    "Dąbrowa Górnicza": "województwo śląskie",
    "Koniecpol": "województwo śląskie",
    "Łodygowice": "województwo śląskie",
    "Siewierz": "województwo śląskie",
    "Wojkowice": "województwo śląskie",
    "Będzin": "województwo śląskie",
    "Kiczyce": "województwo śląskie",
    "Zawiercie": "województwo śląskie",
    "Sławków": "województwo śląskie",
    "Kłobuck": "województwo śląskie",
    "Szczekociny": "województwo śląskie",
    "Włodowice": "województwo śląskie",
    "Skoczów": "województwo śląskie",
    "Bieruń": "województwo śląskie",
    "Nieborowice": "województwo śląskie",
    "Koziegłowy": "województwo wielkopolskie",
    "Korbielów": "województwo śląskie",
    "Łaziska Górne": "województwo śląskie",
    "Harbutowice": "województwo małopolskie",
    "Świętochłowice": "województwo śląskie",
    "Lubliniec": "województwo śląskie",
    "Niegowonice": "województwo śląskie",
    "Wisła Wielka": "województwo śląskie",
    "Czechowice-Dziedzice": "województwo śląskie",
    "Lędziny": "województwo śląskie",
    "Knurów": "województwo śląskie",
    "Kroczyce": "województwo śląskie",
    "Kozy": "województwo śląskie",
    "Radzionków": "województwo śląskie",
    "Strumień": "województwo śląskie",
    "Kolonia": "województwo małopolskie",
    "Mierzyn": "województwo zachodniopomorskie",
    "Korbielów": "województwo śląskie",
    "Łódź": "województwo łódzkie",
    "Węgierska Górka": "województwo śląskie",
    "Piekary Śląskie": "województwo śląskie",
    "Kędzierzyn-Koźle": "województwo opolskie",
    "Suszec": "województwo śląskie",
    "Paczyna": "województwo śląskie",
    "Nakło Śląskie": "województwo śląskie",
    "Leśna": "województwo dolnośląskie",
    "Bujaków": "województwo śląskie",
    "Nieznanice": "województwo śląskie",
    "Koszęcin": "województwo śląskie",
    "Łazy": "województwo śląskie",
    "Mirosław": "województwo wielkopolskie",
    "Bażanowice": "województwo śląskie",
    "Jasienica": "województwo śląskie",
    "Jaworze": "województwo śląskie",
    "Szałsza": "województwo śląskie",
    "Poczesna": "województwo śląskie",
    "Katowice / Dąb": "województwo śląskie",
    "Pruszcz Gdański Ul. Komunalna 2": "województwo pomorskie",
    "Plewiska gm. Komorniki": "województwo wielkopolskie",
    "Herby": "województwo śląskie",
    "Kobiór": "województwo śląskie",
    "Szałsza (pow. tarnogórski)": "województwo śląskie",
    "Poczesna (pow. częstochowski)": "województwo śląskie",
    "Katowice / Dąb": "województwo śląskie",
    "Pruszcz Gdański Ul. Komunalna 2": "województwo pomorskie",
    "Plewiska gm. Komorniki": "województwo wielkopolskie",
    "Blachówka": "województwo opolskie",
    "Kobiór": "województwo śląskie",
    "Imielin": "województwo śląskie",
    "Międzyrzecze Dolne": "województwo śląskie",
    "Radziechowy": "województwo śląskie",
    "Jaroszowice": "województwo małopolskie",
    "Międzyrzecze Górne": "województwo śląskie",
    "Koziegłówki": "województwo śląskie",
    "Konopiska": "województwo śląskie",
    "Chełm Śląski": "województwo śląskie",
    "Studzionka": "województwo śląskie",
    "Wręczyca Wielka": "województwo śląskie",
    "Toszek": "województwo śląskie",
    "Sośnicowice": "województwo śląskie",
    "Ćwiklice": "województwo śląskie",
    "Małe Kozy": "województwo śląskie",
    "Pławniowice": "województwo śląskie",
    "Lgota Murowana": "województwo śląskie",
    "Imielin, Centrum": "województwo śląskie",
    "Woźniki": "województwo śląskie",
    "Poręba": "województwo małopolskie",
    "Gierałtowice": "województwo śląskie",
    "Wisła": "województwo śląskie",
    "Mazańcowice": "województwo śląskie",
    "Aleksandria Druga": "województwo śląskie",
    "Pyskowice": "województwo śląskie",
    "Cięcina": "województwo śląskie",
    "Paniówki": "województwo śląskie",
    "Waleńczów": "województwo śląskie",
    "Nowa Wieś Tworoska": "województwo śląskie",
    "Pogórze": "województwo pomorskie",
    "Tworóg": "województwo śląskie",
    "Orzesze, Centrum": "województwo śląskie",
    "Ornontowice": "województwo śląskie",
    "Ruda": "województwo śląskie",
    "Rudnik Wielki": "województwo śląskie",
    "Jaroszowice": "województwo małopolskie",
    "Świętoszowice": "województwo śląskie",
    "Las": "województwo śląskie",
    "Świbie": "województwo śląskie",
    "Kocierz Moszczanicki": "województwo śląskie",
    "Czaniec": "województwo śląskie",
    "Ogrodzona": "województwo śląskie",
    "Jejkowice": "województwo śląskie",
    "Preczów": "województwo śląskie",
    "Warszowice": "województwo śląskie",
    "Goleszów": "województwo śląskie",
}